version: "3"
services:
  application1:
    image: alpha-java-task3
    ports:
    - "8082:8082"
    depends_on:
      - alfa-battle-task3

  alfa-battle-task3:
    image: postgres
    environment:
      POSTGRES_DB: alfa_battle
      POSTGRES_USER: alfa_battle
      POSTGRES_PASSWORD: qwe123
    ports:
    - 5432:5432
