server:
  port: 8082

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://172.20.0.1:5432/alfa_battle?currentSchema=public
    username: alfa_battle
    password: qwe123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    check-location: true